<?php

namespace Blog\ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Item counter
     * @return mixed
     */
    public function countArticle()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Showing articles
     * @return array
     */
    public function showArticles()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('BlogArticleBundle:Article', 'a')
            ->orderBy('a.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function showOneArticle($id)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('BlogArticleBundle:Article', 'a')
            ->where('a.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }


}
